baseURL = 'https://gavincabbage.com/'
languageCode = 'en-us'
title = 'gavincabbage.com'
ignoreFiles = [".DS_Store", "README.md"]

[params]
  description = 'My website'
  author = 'Gavin Cabbage'

[markup]
  [markup.highlight]
    style = 'github'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['HTML']
  section = ['HTML']
  taxonomy = ['HTML']
  term = ['HTML']
